run_mode: kReal
trigger_mode: kManual
init_motion_enable: true
planner_trigger_lead_time: 0.8
smooth_heading_enable: true
init_motion:
  z_takeoff: 0.0
  z_drop: 0.0
  x_forward: 0.0000

# Group related parameters to be shared between nodes.
RobotDynamics:
  dt: 0.05
  v_max: 1.0
  v_homing_max: 1.0
  yaw_rate_max: 0.4
  v_init_max: 1.0
