world_frame: world
use_tf_transforms: True
use_freespace_pointcloud: True
tsdf_voxels_per_side: 16
tsdf_voxel_size: 0.2
max_ray_length_m: 5.0
min_ray_length_m: 0.8
truncation_distance: 0.4
use_sparsity_compensation_factor: True
sparsity_compensation_factor: 10.0 #10.0
use_weight_dropoff: False
voxel_carving_enabled: True
color_mode: "height"
verbose: False
use_const_weight: True
update_mesh_every_n_sec: 1.0
mesh_min_weight: 1e-4
slice_level: 0.5
method: "fast"
publish_slices: False
publish_pointclouds: True
allow_clear: True
pointcloud_queue_size: 100
min_time_between_msgs_sec: 0.2
#max_block_distance_from_body: FLT_MAX
publish_tsdf_info: False
publish_slices: False
publish_traversable: False
traversability_radius: 1.5
publish_tsdf_map: False
publish_esdf_map: False
enable_icp: False
icp_refine_roll_pitch: False
accumulate_icp_corrections: True
# horizontal_fov: 90.0
# vertical_fov: 90.0 
# near_plane_dist: 0.3
# far_plane_dist: 6.0
# leaf_size: 0.2
